### ISSUE TITLE
What should be in the footer?

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/website#16]
How should our footer look? What needs to be in there? 

Some quick edits that come to mind: 
- move youtube from "Community" to "More" section in the footer

**Comment by Elirudite** [comment]
I think we can put a sitemap or access to our sitemap there. We will have to confirm what pages we will have in the first place though to decide what should be in the footer. 

I really like the navigation suggested (by you or Robert?) below:
- Learn (Educate people about the metaverse)
- Create (Content creation and programming resources)
- Discover (Metaverse platforms/virtual worlds directory)
- Contribute (Descriptions of our projects and how to get involved)

**Comment by humbletim** [comment]
added all currently available community links in for now with #19 -- see #18 for ongoing discussion about overall sitemap
