### ISSUE TITLE
Aug 24th Meeting Action Items

### ISSUE THREAD

**Issue by Elirudite** [omigroup/website#17]
Moving forward for the next version (V3?), we will have a home page with the following sections:
- Initial header w CTA
- What we do (Core Values)
- Trust Signals

As a stretch goal we'd like to include the following sections:
- Why interop matters (Stories and media of interop projects supported by our community)
- Definitions of the metaverse (encouraging people to join the convo, 'We are not the arbiters of truth..')
- Get Involved details (links to discord, funding page, and github)
- Top Navigation (Learn, Create, Discover, Contribute)
- Separate page diving into our core values

Shadow (me) will be transferring my Figma design to the [Glitch markdown page](https://glitch.com/edit/#!/omigroup-website-staging?path=src%2Fpages%2Fhome%2Findex.md%3A1%3A0).
@humbletim will be aggregating the trust signals (news articles) as well as the figjam ideas into a centralized place for accessing/voting.

Verbiage and other details for each section can be finalized after we aggregate everything into one place. 

Please feel free to let us know what else we are missing or if you have further ideas. 

(And let me know if this is the right place/way to use github as this is my first community project 😅 )

**Comment by mrmetaverse** [comment]
Shadow!! Thank you for this!!
