### ISSUE TITLE
Implement Shadow and Jesse James designs from figma 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/website#25]
Apply the next iteration of designs to our website. 

Figma Source: https://www.figma.com/file/7IkelFTsQPpMwzrWGzqFBA/Omigroup-Website?node-id=358%3A70

**Comment by mrmetaverse** [comment]
See: "Shadow's Draft 2" for latest reviewed.  

![image](https://user-images.githubusercontent.com/63426722/133304666-1a551b39-689d-43fa-989e-fb9a5673dbff.png)

**Comment by mrmetaverse** [comment]
@elirudite Also started a third draft, for review: 

![image](https://user-images.githubusercontent.com/63426722/133305288-bd08e866-2d56-472e-b2cf-a1bc5b13aead.png)

**Comment by mrmetaverse** [comment]
@matthewbcool aaaany chance you have an update on implementing this? By the way, we got rid of the glitch staging so its back to raw Github PR submissions.

**Comment by mrmetaverse** [comment]
RE: @matthewbcool  comments about designing responsive components. https://github.com/omigroup/website/issues/23#issuecomment-919588170

**Comment by mrmetaverse** [comment]
Shadows response @elirudite https://github.com/omigroup/website/issues/23#issuecomment-919657381

**Comment by mrmetaverse** [comment]
Do we have an update on the progress of this? @Elirudite and @matthewbcool

**Comment by Elirudite** [comment]
Here is the newest design! Please feel free to share feedback. 

If this is good, than perhaps we can send this to Shaw's team to develop. I'll just need to annotate and turn it into an actual design spec. I can work on making the components in Figma more ready for handoff to the devs if this is the version we want to implement. 

![Shadow's Draft 5 5](https://user-images.githubusercontent.com/10410478/141054144-aef2d1f3-f75a-4c7d-8d5b-43ac70d326a6.png)

**Comment by mrmetaverse** [comment]
@jsejms @Elirudite could you share your most recent mobile design and a quick explainer of yesterday's session? I was going to create a new issue to record yesterday's work but forgot this one already exists. Want to keep it current.

**Comment by mrmetaverse** [comment]
closing due to duplicates
