### ISSUE TITLE
Redesign core values graphic

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/website#30]
How could we design the hub-and-spoke graphic with our core values?

**Comment by mrmetaverse** [comment]
![image](https://user-images.githubusercontent.com/63426722/133476551-43e7accb-3c77-4629-98fe-8fcfb639cfcb.png)

This feels clunky to me. I could use some fresh eyes to tell the story of our core values in an effective way. The hub and spoke design as-is feels dated, cheap, and mildly untrustworthy as an modern and reliable source in our field.

**Comment by mrmetaverse** [comment]
@LightLodges expressed interest in diving into this and other items. I know we have a few designers who would probably be interested as well.

If you could make 1-3 improvements to the graphic as is, what would they be?

**Comment by Elirudite** [comment]
Whatever visual design we land on, I ask that we ensure that links to real-world examples of how we are living/working under each of them. Core Values are often seen/dismissed as just talk. I want to make sure we show that we are real.

**Comment by stonedrew** [comment]
For accessibility considerations for the OMI Spoke graphic: the graphic should be in Tab-able, discrete sections, for screen readers and individual selection, also as clickable buttons for deeper context and user stories connected to these

**Comment by Elirudite** [comment]
We just created a simple list on the website. Perhaps we can reconsider another graphic or add links to the current one on https://omigroup.org

![2022-08-07 11 26 00 omigroup org 49e406f1afc8](https://user-images.githubusercontent.com/10410478/183298479-2c3bb1d0-9a83-4390-b3dc-716a3cdb9c71.png)

**Comment by mrmetaverse** [comment]
> We just created a simple list on the website. Perhaps we can reconsider another graphic or add links to the current one on https://omigroup.org
> 
> ![2022-08-07 11 26 00 omigroup org 49e406f1afc8](https://user-images.githubusercontent.com/10410478/183298479-2c3bb1d0-9a83-4390-b3dc-716a3cdb9c71.png)

CLEAN :soap:
