### ISSUE TITLE
Find new time to meet

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/website#38]
Shadow started a new job! We also have some new members interested in helping with the website work. Let's take a survey to find the new best time to meet, a meeting cadence, and maybe a quick working agreement!

**Comment by mrmetaverse** [comment]
reminding group of this in the discord chat. let's find a new regular time to meet. How about every 2 weeks?

**Comment by Elirudite** [comment]
Yeah it seems Tuesday evening, around 6-8pm EST may work out for us.

**Comment by mrmetaverse** [comment]
Ok I can set it to occur every other week?

**Comment by Elirudite** [comment]
I'm going to close this for now, as we have decided to just work asynchronously until we have need of more regular meetings.
