### ISSUE TITLE
Add vision to website 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/website#40]
Yesterday we voted to ratify our first draft vision statement. We understand that it reads as a mission and will review our mission next. We feel this vision statement reflects our intentions together. 

> _We bolster the metaverse as an open and interoperable resource for anyone, inspired by the collaborative efforts of the community_

**Comment by Elirudite** [comment]
Added it in my most recent iteration of the design draft here: https://github.com/omigroup/website/issues/25#issuecomment-964795818
