### ISSUE TITLE
Finalizing the Website (v1)

### ISSUE THREAD

**Issue by Elirudite** [omigroup/website#48]
Looks like we're finally ready to finalize this first version of the website redesign. 

I'd like to get some feedback as well as help with what should be on this version. Below I've included several versions. 

This version is what I will likely have us develop if we don't get any further help with contributing content. It's a bit plain, but hits all the major things we need to communicate with this first implementation.
![Draft 7 - Truncated w no pics](https://user-images.githubusercontent.com/10410478/147612236-d2e452f3-26db-4ae2-a854-d1ecb7d5a128.png)

This version is Echo's edit (also used above) with all the cards we would love to populate/link out to content from our community. But we will need to confirm all of that content ASAP if we want to implement this soon! I also added my own ideas for card-based core values. If we don't have any content for them, then we can just have those listed out like in the first picture above.
![Echoparadigm Edit - Extended, w pics and core value cards](https://user-images.githubusercontent.com/10410478/147612469-5bfc495d-2e47-4814-b618-053a29d199d9.png)

Finally, here is an unfinished mobile design for this site as well.
![Mobile design](https://user-images.githubusercontent.com/10410478/147612479-8c8f49fb-cc45-4fe7-b083-027df55ccf31.png)

Please let me know what you all think! Especially in regards to how we can get pictures, articles, and other content from our community to populate the site.

I may also add or change a section to show our current ongoing projects, just to make it easier for non-technical people unfamiliar with github to easily see what we are currently working on. 
Similarly, we can have this area mention the active working groups as well.

**Comment by mrmetaverse** [comment]
Man, I love this!! I know Robert is AFK today, but maybe we can set a date as a goal to implement these. @robertlong @matthewbcool either of you up for making these changes by next Wednesday? :eyes:

**Comment by mrmetaverse** [comment]
ant shared that docusaurus is a blocker for them to get involved. Can we use another format? (I think we are switching already)

**Comment by jsejms** [comment]
Website working group met today to discuss content and assets, everything looks to be good.  Next steps implementation from a code perspective, need input from the greater group on what direction we'd like to go, since Docusaurus hasn't been popular.  @antpb @Elirudite @robertlong @fire

**Comment by aiaustin** [comment]
This looking good, and would offer a basis for plenty of content inclusions once the framework is live. Thanks folks.

**Comment by thisisphan** [comment]
Since the esoteric nature of Docusaurus proved to be a blocker, I propose that we choose a widely used SSG. 

Here are the top 9 based on Github stars.
![image](https://user-images.githubusercontent.com/79063400/148262631-525a051d-27a0-4f80-bb97-5c7bb8b789d2.png)

Of all the above options:
- Jekyll is the simplest
- NextJS is the most popular.

Of course, vanilla HTML/CSS/JS is always an option to maximize maintainability.

**Comment by mrmetaverse** [comment]
I have had great experiences with next, and a little Gatsby. I would recommend nextjs x vercel or ghpages

**Comment by thisisphan** [comment]
I can also vouch for Next x Vercel. Great tooling and excellent deployment option.

**Comment by robertlong** [comment]
I've been sipping the Remix Kool-Aid a bit lately and it seems pretty nice. Next is also pretty good. Not a huge fan of Gatsby.

I'm doing a bit more of the CSS tonight with just the HTML + CSS setup I have going

**Comment by robertlong** [comment]
Pushed my work to the main branch. Feel free to check it out. IMO, the spacing and fonts are a bit big. And I still need to do the mobile design.

**Comment by Elirudite** [comment]
Hey @robertlong where can we see this 'main branch'? Which sections seem to big? We can probably make the fonts a size smaller, but that would change everything as I tried to keep them all related. Also, everything is on a grid, so perhaps we can shrink the gutters or something.

**Comment by jsejms** [comment]
> Hey @robertlong where can we see this 'main branch'? Which sections seem to big? We can probably make the fonts a size smaller, but that would change everything as I tried to keep them all related. Also, everything is on a grid, so perhaps we can shrink the gutters or something.

I can show you if you'd like to go over it at some point this week @Elirudite

**Comment by robertlong** [comment]
You can get set up with git pretty easily. Just download Github Desktop and clone this repository. To view the site just open the index.html file. I'd push this to the live site so you can see it there, but I don't think it's quite ready yet.

**Comment by Elirudite** [comment]
Okay I see what you mean! How is this? https://www.figma.com/file/7IkelFTsQPpMwzrWGzqFBA/?node-id=358%3A69
<img width="1440" alt="Draft 8 - Truncated" src="https://user-images.githubusercontent.com/10410478/149626854-4f873661-d33a-4ab9-aa5d-480cf434819c.png">

**Comment by mrmetaverse** [comment]
@antpb could we emphasize _together_ or _we_ instead of **build**? 

Feel like the message is lost in the action word rather than the collectivism. Thoughts? 
![Screenshot_20220120-191803.png](https://user-images.githubusercontent.com/63426722/150442952-6626eed6-44ee-4d76-a785-cd23e062569f.png)

**Comment by antpb** [comment]
@mrmetaverse good call! I like the word "together" being the emphasis. Easy change

**Comment by mrmetaverse** [comment]
New version launched this last week!
