### ISSUE TITLE
People are avoiding streaming the calendar because it is not private

### ISSUE THREAD

**Issue by fire** [omigroup/website#50]
I am avoiding streaming the calendar because it is not private.

Suggestions from the conversation in the discord hack chat is that a website embed link would be more friendly.

Edited

This is detriment to @robertlong and @mrmetaverse 's weekly meetings because people are not reminded of the weekly events.

**Comment by mrmetaverse** [comment]
@fire Would you mind elaborating? The OMI event calendar that you can subscribe too is the issue? How would a "website embed link would be more friendly" work? Is another solution to make the calendar private? Also what are the issues with the calendar being public?

**Comment by mrmetaverse** [comment]
Now I get it... Sorry for the confusion.  

When I clicked on the calendar one day on the stream... it flashed my entire personal calendar, because I happened to be logged in with a gmail account. 

Others are hesitant to stream because they don't want the same thing to happen. And it has happened to a few others in this group.

**Comment by humbletim** [comment]
for reference here is standard and embed style calendar links for comparison:

- [full](https://calendar.google.com/calendar/u/1?cid=Y18wZHB1Z2Y5ZjgzZXE0cWVrbWI2b21xYmptZ0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) (what's on the current websites)
- [embedded](https://calendar.google.com/calendar/embed?src=c_0dpugf9f83eq4qekmb6omqbjmg%40group.calendar.google.com) (in theory only ever shows OMI events)

**Comment by mrmetaverse** [comment]
@antpb has a fix for this as well.

**Comment by antpb** [comment]
Should be fixed now! Thanks for the report!

**Comment by mrmetaverse** [comment]
Thanks everyone!
