### ISSUE TITLE
first blog! Celebrating our one year 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/website#54]
In todays weekly OMI meeting (https://github.com/omigroup/omigroup/discussions/208) @antpb reminded us that we have blogging capability now with our website omigroup.org 

Let's write about our one year anniversary, who we are, what we have been up to, and where we are headed (and how to get involved :joy:)

**Comment by mrmetaverse** [comment]
https://twitter.com/vrhermit/status/1520383294222831618?t=kppPNRRmQidPm_i_Fz_Rnw&s=19

**Comment by Elirudite** [comment]
https://omigroup.org/category/blog/ blog is up!
